# Setup
title:        Personal Page of Yohann Le Faou
tagline:      
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Yohann Le Faou
  url:        https://yohannlefaou.github.io

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown

github_username: YohannLeFaou
